spring:
  application:
    name: challenge-java-developer

  datasource:
    url: jdbc:h2:mem:creditdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 5000
  servlet:
    context-path: /api

logging:
  level:
    org.springframework.web: DEBUG